### ISSUE TITLE
Fix golangci-lint failures in CI workflow: unchecked errors and nil context

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/user-service#11]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The CI linting workflow is failing because golangci-lint detected three code issues: two instances where error return values are not checked (errcheck) and one instance where a nil context is passed instead of context.TODO() (staticcheck).
The CI linting workflow is failing because golangci-lint detected three code issues: two instances where error return values are not checked (errcheck) and one instance where a nil context is passed instead of context.TODO() (staticcheck).

### 2. The GetUser handler in user.go does not check the error return value from json.NewEncoder(w).Encode(user), which could lead to unhandled encoding errors.
The GetUser handler in user.go does not check the error return value from json.NewEncoder(w).Encode(user), which could lead to unhandled encoding errors.

### 3. In the user_test.go file, a nil context is being passed to the GetUser method, which is a bad practice. The staticcheck linter flags this as SA1012.
In the user_test.go file, a nil context is being passed to the GetUser method, which is a bad practice. The staticcheck linter flags this as SA1012.

### Finding 1: The CI linting workflow is failing because golangci-lint detected three code issues: two instances where error return values are not checked (errcheck) and one instance where a nil context is passed instead of context.TODO() (staticcheck).
**Error Log:**

cmd/server/main.go:27:22: Error return value of `zapLogger.Sync` is not checked (errcheck)

**Problematic Code:**

defer zapLogger.Sync()

**Impacted File:** `cmd/server/main.go`

### Finding 2: The GetUser handler in user.go does not check the error return value from json.NewEncoder(w).Encode(user), which could lead to unhandled encoding errors.
**Error Log:**

internal/handler/user.go:45:27: Error return value of `(*encoding/json.Encoder).Encode` is not checked (errcheck)

**Problematic Code:**

json.NewEncoder(w).Encode(user)

**Impacted File:** `internal/handler/user.go`

### Finding 3: In the user_test.go file, a nil context is being passed to the GetUser method, which is a bad practice. The staticcheck linter flags this as SA1012.
**Error Log:**

internal/handler/user_test.go:132:24: SA1012: do not pass a nil Context, even if a function permits it; pass context.TODO if you are unsure about which Context to use (staticcheck)

**Problematic Code:**

got, _ := svc.GetUser(nil, user.Email)

**Impacted File:** `internal/handler/user_test.go`

### Step 2: Since this is in a defer statement, wrap it in an anonymous function:
                   defer func() {
                       if err := zapLogger.Sync(); err != nil {
                           log.Printf("failed to sync logger: %v", err)
                       }
                   }()

### Step 2: Handle the error appropriately:
                   if err := json.NewEncoder(w).Encode(user); err != nil {
                       h.logger.Error("Failed to encode response", zap.Error(err))
                       http.Error(w, "Failed to encode response", http.StatusInternalServerError)
                       return
                   }

### Step 2: Update the code to:
                   got, _ := svc.GetUser(context.TODO(), user.Email)

---

*Confidence level: 95%*
