### ISSUE TITLE
Fix golangci-lint errors in user-service code

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/user-service#15]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The GitHub Actions workflow is failing because the golangci-lint tool is detecting three code quality issues that need to be fixed: 1) In cmd/server/main.go, the error return value of zapLogger.Sync() is not being checked; 2) In internal/handler/user.go, the error return value of json.NewEncoder(w).Encode(user) is not being checked; 3) In internal/handler/user_test.go, a nil Context is being passed to the GetUser function instead of a proper context.
The workflow is failing due to linting errors that need to be fixed.

### 2. The error return value of json.NewEncoder(w).Encode(user) is not being checked in the GetUser handler, which could lead to undetected encoding errors.
The JSON encoding error is not being properly handled.

### 3. In the user_test.go file, a nil Context is being passed to the GetUser function in the TestUpdateUserHandler test, which is a bad practice and could lead to issues with context-aware code.
The test is using nil context which is not recommended.

### Finding 1: The GitHub Actions workflow is failing because the golangci-lint tool is detecting three code quality issues that need to be fixed: 1) In cmd/server/main.go, the error return value of zapLogger.Sync() is not being checked; 2) In internal/handler/user.go, the error return value of json.NewEncoder(w).Encode(user) is not being checked; 3) In internal/handler/user_test.go, a nil Context is being passed to the GetUser function instead of a proper context.
**Error Log:**

##[error]cmd/server/main.go:27:22: Error return value of `zapLogger.Sync` is not checked (errcheck)

**Problematic Code:**

defer zapLogger.Sync()

**Impacted File:** `cmd/server/main.go`

### Finding 2: The error return value of json.NewEncoder(w).Encode(user) is not being checked in the GetUser handler, which could lead to undetected encoding errors.
**Error Log:**

##[error]internal/handler/user.go:45:27: Error return value of `(*encoding/json.Encoder).Encode` is not checked (errcheck)

**Problematic Code:**

json.NewEncoder(w).Encode(user)

**Impacted File:** `internal/handler/user.go`

### Finding 3: In the user_test.go file, a nil Context is being passed to the GetUser function in the TestUpdateUserHandler test, which is a bad practice and could lead to issues with context-aware code.
**Error Log:**

##[error]internal/handler/user_test.go:132:24: SA1012: do not pass a nil Context, even if a function permits it; pass context.TODO if you are unsure about which Context to use (staticcheck)

**Problematic Code:**

got, _ := svc.GetUser(nil, user.Email)

**Impacted File:** `internal/handler/user_test.go`

### Step 1: Modify the defer statement to check and log the error: `defer func() { _ = zapLogger.Sync() }()` or more properly: `defer func() { if err := zapLogger.Sync(); err != nil { log.Printf("failed to sync logger: %v", err) } }()`
Fix the zapLogger.Sync() error handling.

### Step 1: Modify the code to check the error returned by Encode: `if err := json.NewEncoder(w).Encode(user); err != nil { h.logger.Error("Failed to encode response", zap.Error(err)); http.Error(w, "Failed to encode response", http.StatusInternalServerError); return }`
Add proper error handling for JSON encoding.

### Step 1: Replace the nil context with context.TODO() or context.Background(): `got, _ := svc.GetUser(context.TODO(), user.Email)`
Use a proper context instead of nil.

---

*Confidence level: 95%*
